<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Text28_text28</name>
   <tag></tag>
   <elementGuidId>c97ceb2f-68d4-4050-868c-e7346472f2e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text28']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#text28</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>38d762ae-1248-40f9-9611-a40835cf26d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>579850e0-0c24-42c7-bc6c-c14d75bf882a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text28</value>
      <webElementGuid>a39aaebb-b429-4ca2-97dd-ff34e3e60008</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text28&quot;)</value>
      <webElementGuid>4dedb69d-f12f-4175-aff0-f82fc6c461fd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text28']</value>
      <webElementGuid>b2704dd3-95f0-4d3e-ba4e-7390ab3a99f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[28]</value>
      <webElementGuid>f15b2218-5eec-4346-bc86-e1ee597b57a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text28']</value>
      <webElementGuid>6d79953d-c458-4ec3-b3d3-8cc552e0a7e5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
