<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Text37_text37</name>
   <tag></tag>
   <elementGuidId>7a22a226-55cf-4fde-82f2-18a47890ede2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text37']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#text37</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1fa19e0b-f0eb-4edd-91e4-b5cf5930b183</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>24a582fe-ccef-4d06-946e-f86075fb43e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text37</value>
      <webElementGuid>2d0d9b32-f7a1-4e4e-a07f-91be6eff6ef0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text37&quot;)</value>
      <webElementGuid>1889996b-25e6-4c0b-8abd-8bf6e844ad3c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text37']</value>
      <webElementGuid>0a121638-2ab1-42b5-860e-0a62930fcd80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[37]</value>
      <webElementGuid>10ccc7e0-a9ef-42a5-bce9-c69be760b190</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text37']</value>
      <webElementGuid>d675f657-b5e5-466f-ae3d-da0b405aeeb0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
