<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Checkbox4_checkbox5</name>
   <tag></tag>
   <elementGuidId>0201d068-5797-4278-a0f6-e0b3d39c17a5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='checkbox5']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#checkbox5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ab523662-a8e2-49eb-80e4-9ea874969fe8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>d48ded51-8680-4831-b698-2fa3ecc625af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>checkbox5</value>
      <webElementGuid>34be9ea5-5ed3-471b-85ee-0025b892de38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Checkbox5</value>
      <webElementGuid>ed1d692f-91df-483a-b40a-f13eb9ece57c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkbox5&quot;)</value>
      <webElementGuid>af25356a-3c97-4940-80eb-514d307a0f2a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='checkbox5']</value>
      <webElementGuid>aace04e6-1df2-4f28-9aaa-12786f88b34e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[15]</value>
      <webElementGuid>29c06e25-d67a-47b6-9f11-6e8426800a02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'checkbox5']</value>
      <webElementGuid>f7c43df3-250e-470c-8b3b-a94c322aba01</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
