<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Text32_text32</name>
   <tag></tag>
   <elementGuidId>6c74bab4-2a4f-4e02-aa8f-3ecc2c82935e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text32']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#text32</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d12af8c6-c0ac-4a3b-a8f9-8165c631a3a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0c60c8c5-03ea-4b69-a929-642d6c1bb928</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text32</value>
      <webElementGuid>a21d2392-0777-46ae-9633-caafc121d5db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text32&quot;)</value>
      <webElementGuid>e6e4aa74-19a3-43e5-879d-3cc2f67c0327</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text32']</value>
      <webElementGuid>4327deac-2af6-4515-a11c-28bf33f160df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[32]</value>
      <webElementGuid>dd81c66d-04dd-4b02-a10d-e9ed442aaad3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text32']</value>
      <webElementGuid>4fda0820-8a32-47db-ba54-cebb83cd40f3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
