<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Text16_text16</name>
   <tag></tag>
   <elementGuidId>654e6431-3008-4efc-abb2-e308c1aeb2c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text16']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#text16</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>64a07097-ad08-4b5e-ae0a-1ed8cf2899e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6099a29d-ad27-42dd-b21e-dd0c8f370109</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text16</value>
      <webElementGuid>a5589484-1be6-41d7-9851-07de7dcc9d0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text16&quot;)</value>
      <webElementGuid>8de77573-3cab-4135-a1b2-adceb6d5dffc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text16']</value>
      <webElementGuid>125ee56d-eb74-4e84-8f0d-abd0faa4e4fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[16]</value>
      <webElementGuid>e10d8b81-7f0b-4d65-b5e2-359527d1662d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text16']</value>
      <webElementGuid>237d21ba-4b1f-4bc8-ae50-9dfa0f284ea4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
