<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Text35_text35</name>
   <tag></tag>
   <elementGuidId>322c34c3-95f4-4624-ba49-8ed0c4037ef0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text35']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#text35</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>76cdfc13-7689-4395-a441-bd18d24e8932</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c3e72ba6-6d88-4b64-8c47-5cb8173a906f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text35</value>
      <webElementGuid>796b2630-026b-4822-b298-79509831423e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text35&quot;)</value>
      <webElementGuid>24b26ef8-5a42-4b2e-9d1a-a3ff539d6ac0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text35']</value>
      <webElementGuid>60742631-1c0a-4e16-bd00-4c6fdd55e43f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[35]</value>
      <webElementGuid>9d5de284-dca4-4f53-afaa-4bce5317fa70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text35']</value>
      <webElementGuid>b4388ad5-a34c-4475-8ee4-926e8b00077b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
