<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Text36_text36</name>
   <tag></tag>
   <elementGuidId>1c892e35-e1d5-44eb-95fd-63690ca34365</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text36']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#text36</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1f50f6ef-bb6b-44b6-9db0-430790f58fe7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ae14a6c8-34c2-4f16-93be-bd93aca70999</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text36</value>
      <webElementGuid>712e2b9b-65ff-46a5-8aed-dbd1aea07f79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text36&quot;)</value>
      <webElementGuid>b7d481ec-69ea-49a8-9bb1-511f909faf41</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text36']</value>
      <webElementGuid>f675225f-ab40-4517-bb16-a49f8d6b0042</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[36]</value>
      <webElementGuid>3913ed72-f758-46cf-a642-d5e57d4c7bcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text36']</value>
      <webElementGuid>21381e67-ffb5-4b12-a4f5-1a16bf73e3d3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
